  # Application URL
  url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
  
  # Browser Configuration
  browser = chrome
  
  #Credentials
  username = admin
  password = admin123
  
  #ImplicitWait ( In Seconds)
  implicitWait = 10
  
  #ExpliciteWait
  explicitWait = 30
  